name: repository_pattern
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  dio: ^5.1.2
  freezed_annotation: ^2.2.0
  logger: ^1.3.0
  json_annotation: ^4.8.1
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/config/
